spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oexam?allowPublicKeyRetrieval=true&serverTimezone=GMT&characterEncoding=utf8&useSSL=false
    username: root
    password: xxxxx
    driver-class-name: com.mysql.jdbc.Driver
